Repository FRONTENDBOOTCAMP-13th/Final-04-4vely, pull requests merged in 2025-07, with the labels that each got.

#16 Feature/shopping-main-page/sangho
  package-lock.json
  package.json
  public/images/.gitkeep
  public/images/acadia_palenopsis_orchid.webp
  public/images/african_violet_black.webp
  public/images/aglaonema_siam_black.webp
  public/images/alocasia_polly_black.webp
  public/images/baby_gomu.webp
  public/images/baltic_blue_pothos_black.webp
  public/images/bromeliad_black.webp
  public/images/burgundy_rubber_tree_blue.webp
  public/images/calathea_conkina_freddie.webp
  src/app/shop/_components/BookmarkButton.tsx
  src/app/shop/_components/CategoryFilter.tsx
  src/app/shop/_components/ProductCard.tsx
  src/app/shop/page.tsx
  src/components/ui/Accordion.tsx
  src/components/ui/Checkbox.tsx
  src/components/ui/Pagination.tsx
  src/components/ui/Separator.tsx
  src/components/ui/Sheet.tsx
  src/components/ui/Sidebar.tsx
  src/hooks/useMobile.ts
  src/styles/variables.css
  src/types/product.ts
Labels: ✨ feature, 💻 frontend

#21 로그인 페이지 UI 구현
  src/app/(auth)/login/page.tsx
  src/app/(purchase)/cart/page.tsx
  src/app/layout.tsx
  src/app/navigation/page.tsx
  src/assets/images/login_plant_character.webp
  src/components/layout/Header.tsx
  src/components/ui/Checkbox.tsx
  src/components/ui/Dialog.tsx
  src/components/ui/Input.tsx
  src/styles/globals.css
Labels: ✨ feature, 💻 frontend

#24 Feature/product-details-page/sangho
  src/app/layout.tsx
  src/app/shop/_components/ProductCard.tsx
  src/app/shop/page.tsx
  src/app/shop/products/[id]/_components/Badge.tsx
  src/app/shop/products/[id]/_components/ProductDetailCard.tsx
  src/app/shop/products/[id]/page.tsx
Labels: ✨ feature, 💻 frontend

#27 🐳 chore: Installing Sharp Dependency for Deployment Error Resolution
  package-lock.json
  package.json
Labels: 🐛 bugfix, 🌏 deployment

#29 1차 배포테스트(오류 수정 후 재배포)
  package-lock.json
  package.json
  src/app/shop/products/[id]/page.tsx
Labels: 🌏 deployment

#33 메인 홈 페이지 UI 작업
  package-lock.json
  package.json
  public/images/.gitkeep
  public/images/hibiscus_white.webp
  public/images/olive_tree_gray.webp
  public/images/watering_can.webp
  src/app/curation/[slug]/page.tsx
  src/app/curation/page.tsx
  src/app/example/button/page.tsx
  src/app/page.tsx
  src/assets/images/hero.webp
  src/assets/images/rain.webp
  src/components/_home/CommunityPop.tsx
  src/components/_home/CurationCarousel.tsx
  src/components/_home/ReviewCarousel.tsx
  src/components/_home/shop-new/NewProductSection.tsx
  src/components/ui/Button.tsx
  src/components/ui/Card.tsx
  src/components/ui/Carousel.tsx
Labels: 🚨 P1: High, ✨ feature, 💻 frontend, 🎨 UI/UX

#41 Feature/shop main/sangho
  src/app/shop/_components/CategoryFilter.tsx
  src/app/shop/_components/ProductCard.tsx
  src/app/shop/page.tsx
  src/app/shop/products/[id]/_components/ProductDetailCard.tsx
Labels: ✨ feature, 💻 frontend

#42 feature/my-page/hyunsoo
  src/app/my-page/bookmarks/layout.tsx
  src/app/my-page/bookmarks/posts/page.tsx
  src/app/my-page/bookmarks/products/page.tsx
  src/app/my-page/my-plants/[plantId]/_components/EmptyDiaryState.tsx
  src/app/my-page/my-plants/[plantId]/_components/PlantHeader.tsx
  src/app/my-page/my-plants/[plantId]/page.tsx
  src/app/my-page/my-plants/_components/PlantRegisterModal.tsx
  src/app/my-page/my-plants/_hooks/useImageUpload.ts
  src/app/my-page/my-plants/page.tsx
  src/app/my-page/order-history/page.tsx
Labels: ✨ feature, 🎨 UI/UX

#43 hofix/deloy/hyunsoo
  package-lock.json
  src/app/curation/[slug]/page.tsx
Labels: 🐛 bugfix

#45 hofix/deloy/hyunsoo
  package-lock.json
  package.json
  public/images/cat_palm_gray.webp
Labels: 🌏 deployment

#52 Feature/product-data/sangho
  src/app/shop/_components/BookmarkButton.tsx
  src/app/shop/_components/CategoryFilter.tsx
  src/app/shop/_components/ProductCard.tsx
  src/app/shop/_components/ShopClientContent.tsx
  src/app/shop/page.tsx
  src/app/shop/products/[id]/_components/Badge.tsx
  src/app/shop/products/[id]/_components/ProductDetailCard.tsx
  src/app/shop/products/[id]/_components/ProductDetailClient.tsx
  src/app/shop/products/[id]/page.tsx
  src/lib/api/dbinit/team/data.js
  src/lib/api/dbinit/team/uploadFiles/Skynapsus.webp
  src/lib/api/dbinit/team/uploadFiles/Zamioculcas.webp
  src/lib/api/dbinit/team/uploadFiles/baby_gomu.webp
  src/lib/api/dbinit/team/uploadFiles/calathea_conkina_freddie.webp
  src/lib/api/dbinit/team/uploadFiles/english_ivy.webp
  src/lib/api/dbinit/team/uploadFiles/gomu_tree.webp
  src/lib/api/dbinit/team/uploadFiles/guzmania.webp
  src/lib/api/dbinit/team/uploadFiles/india_gomu_tree.webp
  src/lib/api/dbinit/team/uploadFiles/little_light_black.webp
  src/lib/api/dbinit/team/uploadFiles/little_light_white.webp
  src/lib/api/dbinit/team/uploadFiles/middle_light_black.webp
  src/lib/api/dbinit/team/uploadFiles/middle_light_white.webp
  src/lib/api/dbinit/team/uploadFiles/monstera.webp
  src/lib/api/dbinit/team/uploadFiles/monstera_thai_constellation.webp
  src/lib/api/dbinit/team/uploadFiles/peperomia_optusifolia.webp
  src/lib/api/dbinit/team/uploadFiles/phileas_peperomeoides.webp
  src/lib/api/dbinit/team/uploadFiles/skynapsus_pictus.webp
  src/lib/api/dbinit/team/uploadFiles/swiss_cheese_monstera.webp
  src/lib/api/dbinit/team/uploadFiles/table_yaja.webp
  src/lib/functions/market.ts
  src/store/bookmarkStore.ts
  src/types/product.ts
Labels: 📬 API, 💻 frontend

#59 feature/my page/hyunsoo
  next.config.ts
  package-lock.json
  package.json
  src/app/(auth)/login/_components/LoginToast.tsx
  src/app/(auth)/login/page.tsx
  src/app/layout.tsx
  src/app/my-page/_components/MyPageNav.tsx
  src/app/my-page/layout.tsx
  src/app/my-page/my-plants/_components/PlantCard.tsx
  src/app/my-page/my-plants/_components/PlantList.tsx
  src/app/my-page/my-plants/_components/PlantRegisterModal.tsx
  src/app/my-page/my-plants/page.tsx
  src/app/my-page/profile/_components/ProfileClient.tsx
  src/app/my-page/profile/page.tsx
  src/app/shop/_components/ShopClientContent.tsx
  src/app/unauthorized/_components/UnauthorizedClient.tsx
  src/app/unauthorized/page.tsx
  src/components/layout/Header.tsx
  src/hooks/useLoginForm.ts
  src/hooks/useLoginToast.ts
  src/lib/api/actions/fileActions.ts
  src/lib/api/actions/plantActions.ts
  src/lib/api/actions/userActions.ts
  src/lib/functions/authFunctions.ts
  src/lib/functions/userFunctions.ts
  src/middleware.ts
  src/store/authStore.ts
  src/types/auth.types.ts
  src/types/file.types.ts
  src/types/post.types.ts
Labels: ✨ feature, 📬 API

#60 📬 api: Simplified data.js, testing Bruno API
  src/lib/api/bruno/team/01_회원/01_회원가입,로그인/folder.bru
  src/lib/api/bruno/team/01_회원/04_회원 정보 조회/folder.bru
  src/lib/api/bruno/team/01_회원/folder.bru
  src/lib/api/bruno/team/05_게시판(QnA, 공지 등)/folder.bru
  src/lib/api/bruno/team/06_시스템/folder.bru
  src/lib/api/bruno/team/게시판(QnA, 공지 등)/folder.bru
  src/lib/api/bruno/team/게시판(QnA, 공지 등)/게시물 등록.bru
  src/lib/api/bruno/team/게시판(QnA, 공지 등)/게시물 삭제.bru
  src/lib/api/bruno/team/게시판(QnA, 공지 등)/게시물 상세 조회.bru
  src/lib/api/bruno/team/게시판(QnA, 공지 등)/게시물 수정.bru
  src/lib/api/bruno/team/게시판(QnA, 공지 등)/목록 조회/folder.bru
  src/lib/api/bruno/team/게시판(QnA, 공지 등)/목록 조회/게시물 목록 조회.bru
  src/lib/api/bruno/team/상품/folder.bru
  src/lib/api/bruno/team/상품/상품 목록 조회.bru
  src/lib/api/bruno/team/시스템/folder.bru
  src/lib/api/bruno/team/시스템/파일/folder.bru
  src/lib/api/bruno/team/시스템/파일/파일 업로드.bru
  src/lib/api/bruno/team/회원/folder.bru
  src/lib/api/bruno/team/회원/회원 정보 조회/folder.bru
  src/lib/api/bruno/team/회원/회원 정보 조회/지정한 회원 정보 조회(모든 속성).bru
  src/lib/api/bruno/team/회원/회원가입,로그인/folder.bru
  src/lib/api/bruno/team/회원/회원가입,로그인/관리자 로그인(_id=1).bru
  src/lib/api/bruno/team/회원/회원가입,로그인/회원 가입.bru
  src/lib/api/bruno/team/회원/회원가입,로그인/회원 로그인(_id=2).bru
  src/lib/api/dbinit/team/data.js
Labels: 📬 API

#63 홈 페이지 날씨 API 연결
  bruno/team/상품/상품 검색 (custom 속성 사용).bru
  public/images/clear.webp
  public/images/cloud.webp
  public/images/default.webp
  public/images/mist.webp
  public/images/rain.webp
  public/images/snow.webp
  public/images/thunderstorm.webp
  src/app/page.tsx
  src/components/_home/CommunityPop.tsx
  src/components/_home/NewProductSection.tsx
  src/components/_home/ReviewCarousel.tsx
  src/components/_home/WeatherWidget.tsx
  src/lib/api/weather.ts
  src/lib/functions/weather/fetchWeather.ts
  src/lib/functions/weather/mapWeatherToTips.ts
  src/lib/functions/weather/plantByWeather.ts
  src/lib/utils/weaterImage.ts
Labels: 🚨 P1: High, ✨ feature, 📬 API, 💻 frontend, 🎨 UI/UX

#65 Feature/product detail fn/sangho
  src/app/(purchase)/cart/_components/CartClient.tsx
  src/app/(purchase)/cart/page.tsx
  src/app/(purchase)/order/_components/orderClient.tsx
  src/app/(purchase)/order/order-complete/page.tsx
  src/app/(purchase)/order/page.tsx
  src/app/community/page.tsx
  src/app/shop/_components/BookmarkButton.tsx
  src/app/shop/_components/CategoryFilter.tsx
  src/app/shop/_components/ProductCard.tsx
  src/app/shop/_components/ShopClientContent.tsx
  src/app/shop/page.tsx
  src/app/shop/products/[id]/_components/Badge.tsx
  src/app/shop/products/[id]/_components/ProductDetailCard.tsx
  src/app/shop/products/[id]/_components/ProductDetailClient.tsx
  src/app/shop/products/[id]/_components/ReviewItem.tsx
  src/app/shop/products/[id]/_components/ReviewSection.tsx
  src/app/shop/products/[id]/page.tsx
  src/components/_home/NewProductSection.tsx
  src/components/ui/BookmarkButton.tsx
  src/lib/actions/bookmarkServerActions.ts
  src/lib/actions/cartServerActions.ts
  src/lib/actions/orderServerActions.ts
  src/lib/actions/reviewServerActions.ts
  src/lib/functions/bookmarkServerFunctions.ts
  src/lib/functions/market.ts
  src/lib/functions/productClientFunctions.ts
  src/lib/functions/productServerFunctions.ts
  src/lib/functions/reviewServerFunctions.ts
  src/store/bookmarkStore.ts
  src/store/cartStore.ts
  src/types/bookmark.types.ts
  src/types/cart.types.ts
  src/types/order.types.ts
  src/types/product.ts
  src/types/product.types.ts
  src/types/review.types.ts
Labels: ✨ feature, 📬 API, 💻 frontend

#66 feature/my-page/hyunsoo
  bruno/team/게시판(QnA, 공지 등)/목록 조회/게시물 목록 조회.bru
  dbinit/team/data.js
  package-lock.json
  public/images/placeholder-plant.svg
  src/app/my-page/bookmarks/products/_components/BookmarkProductsList.tsx
  src/app/my-page/bookmarks/products/_components/ErrorDisplay.tsx
  src/app/my-page/bookmarks/products/_components/ProductCard.tsx
  src/app/my-page/bookmarks/products/page.tsx
  src/lib/actions/plantActions.ts
  src/lib/functions/bookmarkFunctions.ts
  src/lib/functions/userFunctions.ts
  src/lib/utils/auth.server.ts
Labels: 📬 API

#71 매거진 페이지 UI 작업
  src/app/curation/[slug]/page.tsx
  src/app/curation/page.tsx
  src/app/green-magazine/[id]/page.tsx
  src/app/green-magazine/_components/MagazineCard.tsx
  src/app/green-magazine/page.tsx
  src/app/page.tsx
  src/components/_home/GreenMagazineCarousel.tsx
  src/components/_home/NewProductSection.tsx
  src/components/_home/ReviewCarousel.tsx
  src/components/_home/WeatherWidget.tsx
  src/constants/header.constants.ts
  src/lib/functions/weather/fetchWeather.ts
  src/lib/functions/weather/mapWeatherToTips.ts
  src/lib/functions/weather/plantByWeather.ts
Labels: 💻 frontend, 🎨 UI/UX, ♻️ refactor

#74 Feature/cart fn/sangho
  src/app/(purchase)/cart/_components/CartClient.tsx
  src/app/(purchase)/cart/page.tsx
  src/app/(purchase)/order/_components/orderClient.tsx
  src/app/(purchase)/order/page.tsx
  src/app/shop/products/[id]/_components/ProductDetailClient.tsx
  src/app/shop/products/[id]/_components/ReviewItem.tsx
  src/lib/actions/cartServerActions.ts
  src/types/cart.types.ts
Labels: ✨ feature, 📬 API, 💻 frontend, 🎨 UI/UX

#76 feature/order-list/hyunsoo
  src/app/(purchase)/cart/_components/CartClient.tsx
  src/app/(purchase)/order/_components/orderClient.tsx
  src/app/community/page.tsx
  src/app/loading.tsx
  src/app/my-page/_components/ErrorDisplay.tsx
  src/app/my-page/bookmarks/layout.tsx
  src/app/my-page/bookmarks/posts/_components/BookmarkPostsList.tsx
  src/app/my-page/bookmarks/posts/_components/ErrorDisplay.tsx
  src/app/my-page/bookmarks/posts/page.tsx
  src/app/my-page/bookmarks/products/_components/AddToCartDialog.tsx
  src/app/my-page/bookmarks/products/_components/BookmarkProductsList.tsx
  src/app/my-page/bookmarks/products/_components/CartConfirmDialog.tsx
  src/app/my-page/bookmarks/products/_components/ProductCard.tsx
  src/app/my-page/bookmarks/products/page.tsx
  src/app/my-page/loading.tsx
  src/app/my-page/my-plants/[plantId]/_components/PlantDiaryClientWrapper.tsx
  src/app/my-page/my-plants/_components/MyPlantsClient.tsx
  src/app/my-page/my-plants/_components/MyPlantsClientWrapper.tsx
  src/app/my-page/my-plants/_components/PlantCard.tsx
  src/app/my-page/my-plants/_components/PlantRegisterModal.tsx
  src/app/my-page/my-plants/_components/PlantSortSelect.tsx
  src/app/my-page/my-plants/_utils/plantUtils.ts
  src/app/my-page/my-plants/page.tsx
  src/app/my-page/order-history/_components/OrderHistoryCard.tsx
  src/app/my-page/order-history/_components/OrderHistoryList.tsx
  src/app/my-page/order-history/_components/ReviewForm.tsx
  src/app/my-page/order-history/_hooks/useOrderDeliveryStatus.ts
  src/app/my-page/order-history/_types/index.ts
  src/app/my-page/order-history/page.tsx
  src/app/my-page/order-history/utils/orderUtils.ts
  src/app/my-page/profile/_components/ProfileClient.tsx
  src/lib/actions/diaryActions.ts
  src/lib/actions/orderReviewServerActions.ts
  src/lib/actions/plantActions.ts
  src/lib/functions/mypage/bookmarkApi.ts
  src/lib/functions/mypage/bookmarkFunctions.ts
  src/lib/functions/mypage/bookmarkTransformers.ts
  src/lib/functions/mypage/bookmarkUtils.ts
  src/lib/functions/orderFunctions.ts
  src/lib/utils/auth.client.ts
  src/lib/utils/auth.server.ts
  src/types/review.types.ts
Labels: ✨ feature, 📬 API, 💻 frontend

#68 feature/community-page/junhwan
  src/app/community/[id]/_components/ClientDetail.tsx
  src/app/community/[id]/_components/DeleteButton.tsx
  src/app/community/[id]/_components/UpdateButton.tsx
  src/app/community/[id]/edit/_components/ClientEdit.tsx
  src/app/community/[id]/edit/page.tsx
  src/app/community/[id]/page.tsx
  src/app/community/_components/ClientCommunity.tsx
  src/app/community/page.tsx
  src/app/community/write/_components/ClientWrite.tsx
  src/app/community/write/page.tsx
  src/lib/actions/communityActions.ts
  src/lib/functions/communityFunctions.ts
  src/types/commnunity.types.ts
Labels: ✨ feature, 📬 API, 💻 frontend

#82 feature/sign-up/hyunsoo
  package-lock.json
  package.json
  src/app/(auth)/sign-up/[step]/SignUpStepClient.tsx
  src/app/(auth)/sign-up/[step]/page.tsx
  src/app/(auth)/sign-up/_components/common/ErrorDisplay.tsx
  src/app/(auth)/sign-up/_components/common/RouteChangeHandler.tsx
  src/app/(auth)/sign-up/_components/common/WizardProgress.tsx
  src/app/(auth)/sign-up/_components/forms/AgreementCheckbox.tsx
  src/app/(auth)/sign-up/_components/forms/ImageUpload.tsx
  src/app/(auth)/sign-up/_components/forms/PasswordStrengthIndicator.tsx
  src/app/(auth)/sign-up/_components/steps/PersonalInfoStep.tsx
  src/app/(auth)/sign-up/_components/steps/ProfileSetupStep.tsx
  src/app/(auth)/sign-up/_components/steps/TermsAgreementStep.tsx
  src/app/(auth)/sign-up/_hooks/useSignUpForm.ts
  src/app/(auth)/sign-up/_schemas/index.ts
  src/app/(auth)/sign-up/_types/index.ts
  src/app/(auth)/sign-up/layout.tsx
  src/app/(auth)/sign-up/page.tsx
  src/app/my-page/_components/LoadingRouter.tsx
  src/app/my-page/_components/skeletons/BookmarkSkeletonUI.tsx
  src/app/my-page/_components/skeletons/MyPlantsSkeletonUI.tsx
  src/app/my-page/_components/skeletons/OrderHistorySkeletonUI.tsx
  src/app/my-page/_components/skeletons/ProfileSkeletonUI.tsx
  src/app/my-page/bookmarks/_components/BookmarksNavigation.tsx
  src/app/my-page/bookmarks/layout.tsx
  src/app/my-page/loading.tsx
  src/app/my-page/my-plants/_components/MyPlantsClient.tsx
  src/app/my-page/my-plants/_components/MyPlantsClientWrapper.tsx
  src/app/my-page/my-plants/page.tsx
  src/components/layout/Header.tsx
  src/lib/actions/fileActions.ts
  src/lib/functions/authFunctions.ts
  src/store/signUpStore.ts
  src/types/auth.types.ts
Labels: ✨ feature, 📬 API, 💻 frontend, ♻️ refactor
