Repository FRONTENDBOOTCAMP-13th/Final-04-4vely, pull requests merged in 2025-08, with the labels that each got.

#85 Feature/payment fn/sangho
  dbinit/team/data.js
  package-lock.json
  package.json
  src/app/(purchase)/cart/_components/CartClient.tsx
  src/app/(purchase)/cart/page.tsx
  src/app/(purchase)/order/_components/orderClient.tsx
  src/app/(purchase)/order/order-complete/page.tsx
  src/app/(purchase)/order/page.tsx
  src/app/shop/_components/CategoryFilter.tsx
  src/app/shop/_components/ProductCard.tsx
  src/app/shop/_components/ShopClientContent.tsx
  src/app/shop/page.tsx
  src/app/shop/products/[id]/_components/ProductDetailCard.tsx
  src/app/shop/products/[id]/_components/ProductDetailClient.tsx
  src/app/shop/products/[id]/_components/ReviewItem.tsx
  src/app/shop/products/[id]/_components/ReviewSection.tsx
  src/app/shop/products/[id]/page.tsx
  src/components/ui/BookmarkButton.tsx
  src/constants/header.constants.ts
  src/lib/actions/cartServerActions.ts
  src/lib/actions/order/orderServerActions.ts
  src/lib/actions/order/paymentServerActions.ts
  src/lib/actions/shop/bookmarkServerActions.ts
  src/lib/actions/shop/reviewServerActions.ts
  src/lib/functions/productServerFunctions.ts
  src/lib/functions/shop/bookmarkServerFunctions.ts
  src/lib/functions/shop/productClientFunctions.ts
  src/lib/functions/shop/productServerFunctions.ts
  src/lib/functions/shop/reviewServerFunctions.ts
  src/types/cart.types.ts
  src/types/order.types.ts
  src/types/payment.types.ts
  src/types/product.types.ts
Labels: ✨ feature, 📬 API, 💻 frontend, 🎨 UI/UX

#87 📬 api: Create data initialization json format and bruno file
  bruno/team/데이터 초기화/DB 초기화.bru
  bruno/team/데이터 초기화/folder.bru
  dbinit/team/data.json
Labels: 📬 API

#84 feature/my-page-post/hyunsoo
  bruno/team/주문/folder.bru
  bruno/team/주문/주문 목록 조회.bru
  dbinit/team/data.json
  package-lock.json
  src/app/(auth)/sign-up/_components/common/ErrorDisplay.tsx
  src/app/my-page/bookmarks/posts/_components/BookmarkPostsList.tsx
  src/app/my-page/bookmarks/posts/_components/PostCard.tsx
  src/app/my-page/bookmarks/posts/page.tsx
  src/app/my-page/bookmarks/products/_components/AddToCartDialog.tsx
  src/app/my-page/bookmarks/products/_components/BookmarkProductsList.tsx
  src/app/my-page/bookmarks/products/_components/ProductCard.tsx
  src/app/my-page/bookmarks/products/page.tsx
  src/app/my-page/my-plants/[plantId]/_components/DiaryCard.tsx
  src/app/my-page/my-plants/[plantId]/_components/PlantDiaryClientWrapper.tsx
  src/app/my-page/my-plants/[plantId]/page.tsx
  src/app/my-page/my-plants/_components/MyPlantsClient.tsx
  src/app/my-page/my-plants/_components/PlantRegisterModal.tsx
  src/app/my-page/my-plants/_hooks/useDiaryData.ts
  src/app/my-page/my-plants/_hooks/usePlantData.ts
  src/app/my-page/my-plants/_types/diary.types.ts
  src/app/my-page/my-plants/_utils/plantUtils.ts
  src/app/my-page/my-plants/page.tsx
  src/app/my-page/order-history/_components/OrderHistoryCard.tsx
  src/app/my-page/order-history/_components/OrderHistoryList.tsx
  src/app/my-page/order-history/_components/ReviewForm.tsx
  src/app/my-page/order-history/_types/index.ts
  src/app/my-page/order-history/page.tsx
  src/app/my-page/order-history/utils/orderUtils.ts
  src/app/my-page/profile/_components/ChangePasswordDialog.tsx
  src/app/my-page/profile/_components/ProfileClient.tsx
  src/app/my-page/profile/page.tsx
  src/components/ui/Pagination.tsx
  src/components/ui/PaginationWrapper.tsx
  src/lib/actions/mypage/bookmark/bookmarkActions.ts
  src/lib/actions/mypage/myPlant/diaryActions.ts
  src/lib/actions/mypage/myPlant/plantActions.ts
  src/lib/actions/mypage/orderList/orderReviewServerActions.ts
  src/lib/actions/mypage/profile/userActions.ts
  src/lib/functions/mypage/bookmark/bookmarkApi.ts
  src/lib/functions/mypage/bookmark/bookmarkFunctions.ts
  src/lib/functions/mypage/bookmark/bookmarkTransformers.ts
  src/lib/functions/mypage/bookmark/bookmarkUtils.ts
  src/lib/functions/mypage/orderList/orderFunctions.ts
  src/lib/functions/mypage/profile/userFunctions.ts
  src/lib/utils/auth.client.ts
  src/types/mypageBookmark.types.ts
Labels: 📬 API, 🧪 test, 🐛 bugfix, ♻️ refactor

#106 🐛 bugfix: state that it is a dynamic file
  src/app/(purchase)/order/page.tsx
Labels: 🐛 bugfix

#109 배포 2차 테스트
  src/app/(purchase)/order/page.tsx
  src/components/_home/ReviewCarousel.tsx
  src/components/_home/weather/WeatherWidget.tsx
  src/lib/functions/home/getReviewPopPosts.ts
Labels: 🌏 deployment

#111 Feature/my page login qa/hyunsoo
  src/app/layout.tsx
  src/app/my-page/profile/_components/ProfileClient.tsx
  src/auth.ts
  src/components/layout/ActivityTracker.tsx
  src/components/layout/Header.tsx
  src/components/ui/AlertDialog.tsx
  src/components/ui/Dialog.tsx
  src/hooks/useActivityTracker.ts
  src/lib/functions/authFunctions.ts
  src/lib/functions/shop/reviewServerFunctions.ts
  src/store/authStore.ts
  src/types/user.types.ts
Labels: 🐛 bugfix

#113 Bugfix/cart order page/sangho
  src/app/(purchase)/cart/page.tsx
  src/app/(purchase)/order/_components/orderClient.tsx
  src/app/(purchase)/order/order-complete/page.tsx
  src/app/(purchase)/order/page.tsx
  src/app/shop/_components/ShopClientContent.tsx
  src/app/shop/page.tsx
  src/app/shop/products/[id]/_components/ProductDetailClient.tsx
  src/app/shop/products/[id]/page.tsx
  src/components/ui/BookmarkButton.tsx
  src/lib/actions/cartServerActions.ts
  src/lib/actions/order/orderServerActions.ts
  src/lib/actions/order/paymentServerActions.ts
  src/lib/actions/shop/bookmarkServerActions.ts
  src/lib/actions/shop/reviewServerActions.ts
  src/lib/functions/shop/bookmarkServerFunctions.ts
  src/lib/functions/shop/productClientFunctions.ts
  src/lib/functions/shop/productServerFunctions.ts
  src/lib/functions/shop/reviewServerFunctions.ts
Labels: 📬 API, 🐛 bugfix, 🎨 UI/UX

#116 feature/my-page-login-qa/hyunsoo
  package.json
  src/app/(auth)/login/_components/SocialLogin.tsx
  src/app/my-page/_components/skeletons/BookmarkSkeletonUI.tsx
  src/app/my-page/bookmarks/posts/_components/BookmarkPostsList.tsx
  src/app/my-page/bookmarks/posts/_components/PostCard.tsx
  src/app/my-page/bookmarks/posts/loading.tsx
  src/app/my-page/bookmarks/posts/page.tsx
  src/app/my-page/bookmarks/products/_components/BookmarkProductsList.tsx
  src/app/my-page/bookmarks/products/_components/ProductCard.tsx
  src/app/my-page/bookmarks/products/loading.tsx
  src/app/my-page/bookmarks/products/page.tsx
  src/app/my-page/layout.tsx
  src/app/my-page/my-plants/[plantId]/_components/DiaryModal.tsx
  src/app/my-page/my-plants/_components/EmptyPlantCard.tsx
  src/app/my-page/my-plants/_components/MyPlantsClient.tsx
  src/app/my-page/my-plants/_components/PlantList.tsx
  src/app/my-page/my-plants/_components/PlantRegisterModal.tsx
  src/app/my-page/my-plants/page.tsx
  src/app/my-page/order-history/_components/OrderHistoryCard.tsx
  src/app/my-page/order-history/_components/OrderHistoryList.tsx
  src/app/my-page/order-history/loading.tsx
  src/app/my-page/order-history/page.tsx
  src/app/my-page/profile/_components/ChangePasswordDialog.tsx
  src/app/my-page/profile/_components/ProfileClient.tsx
  src/app/my-page/profile/page.tsx
  src/components/ui/PaginationWrapper.tsx
  src/hooks/useActivityTracker.ts
  src/hooks/useLoginForm.ts
  src/lib/actions/mypage/profile/userActions.ts
  src/lib/functions/mypage/bookmark/bookmarkApi.ts
  src/lib/functions/mypage/bookmark/bookmarkFunctions.ts
  src/lib/functions/mypage/bookmark/bookmarkTransformers.ts
  src/lib/functions/mypage/bookmark/bookmarkUtils.ts
  src/store/authStore.ts
Labels: 📬 API, 🐛 bugfix, 💻 frontend, ♻️ refactor

#117 커뮤니티 인기글 정렬 수정 및 홈 UI 변경
  bruno/team/게시판(QnA, 공지 등)/목록 조회/게시물 목록 조회.bru
  bruno/team/게시판(QnA, 공지 등)/북마크-좋아요 목록 조회.bru
  bruno/team/게시판(QnA, 공지 등)/좋아요 추가.bru
  src/app/layout.tsx
  src/components/_home/CommunityPop.tsx
  src/components/_home/ReviewCarousel.tsx
  src/components/_home/green-magazine/GreenMagazineCarousel.tsx
  src/components/layout/Header.tsx
  src/components/ui/Card.tsx
  src/lib/functions/home/getCommunityPopPosts.ts
  src/lib/functions/home/getReviewPopPosts.ts
  src/types/reviewPop.types.ts
Labels: ✨ feature, 📬 API, 🌏 deployment, 🎨 UI/UX

#121 🐛 bugfix: shipping memo z-index
  src/app/(purchase)/order/_components/orderClient.tsx
Labels: 🐛 bugfix

#130 Feature/feature/order status/hyunsoo
  src/app/admin/analytics/page.tsx
  src/app/admin/layout.tsx
  src/app/admin/orders/_components/OrdersClient.tsx
  src/app/admin/orders/page.tsx
  src/app/admin/page.tsx
  src/app/admin/products/[id]/page.tsx
  src/app/admin/products/page.tsx
  src/app/admin/users/page.tsx
  src/app/api/orders/[id]/route.ts
  src/app/example/avatar/page.tsx
  src/app/example/button/page.tsx
  src/app/example/card/page.tsx
  src/app/example/header-footer/page.tsx
  src/app/example/input/page.tsx
  src/app/example/page.tsx
  src/app/example/select/page.tsx
  src/app/layout.tsx
  src/app/navigation/page.tsx
  src/components/layout/ConditionalLayout.tsx
  src/hooks/useActivityTracker.ts
  src/lib/actions/admin/orderActions.ts
  src/lib/actions/order/orderSchedulerActions.ts
  src/lib/functions/authFunctions.ts
  src/store/authStore.ts
Labels: ✨ feature, 📬 API, 💻 frontend

#132 배포 테스트입니다!
  README.md
  src/app/admin/analytics/page.tsx
  src/app/admin/layout.tsx
  src/app/admin/orders/_components/OrdersClient.tsx
  src/app/admin/orders/page.tsx
  src/app/admin/page.tsx
  src/app/admin/products/[id]/page.tsx
  src/app/admin/products/page.tsx
  src/app/admin/users/page.tsx
  src/app/api/orders/[id]/route.ts
  src/app/community/[id]/edit/_components/ClientEdit.tsx
  src/app/community/write/_components/ClientWrite.tsx
  src/app/example/avatar/page.tsx
  src/app/example/button/page.tsx
  src/app/example/card/page.tsx
  src/app/example/header-footer/page.tsx
  src/app/example/input/page.tsx
  src/app/example/page.tsx
  src/app/example/select/page.tsx
  src/app/layout.tsx
  src/app/navigation/page.tsx
  src/components/layout/ConditionalLayout.tsx
  src/hooks/useActivityTracker.ts
  src/lib/actions/admin/orderActions.ts
  src/lib/actions/order/orderSchedulerActions.ts
  src/lib/functions/authFunctions.ts
  src/store/authStore.ts
Labels: 🌏 deployment

#137 최종 배포입니다
  README.md
  bruno/team/데이터 초기화/DB 초기화.bru
  dbinit/team/data.json
  src/app/community/[id]/_components/ClientDetail.tsx
  src/app/community/[id]/_components/DeleteButton.tsx
  src/app/community/[id]/_components/UpdateButton.tsx
  src/app/community/[id]/edit/_components/ClientEdit.tsx
  src/app/community/[id]/page.tsx
  src/app/community/_components/ClientCommunity.tsx
  src/app/community/write/_components/ClientWrite.tsx
  src/app/green-magazine/_components/MagazineCard.tsx
  src/app/green-magazine/_components/MagazineDetailContent.tsx
  src/assets/icons/.gitkeep
  src/assets/images/hero.webp
  src/assets/images/hoya_heart_brown.webp
  src/assets/images/login_plant_character.webp
  src/assets/images/rain.webp
  src/components/ui/BookmarkButton.tsx
  src/constants/header.constants.ts
  src/lib/actions/shop/bookmarkServerActions.ts
Labels: 🌏 deployment

#139 찐 최종 배포입니다.
  src/app/(auth)/login/page.tsx
  src/app/admin/orders/_components/OrdersClient.tsx
  src/components/_home/weather/WeatherWidget.tsx
  src/components/ui/Table.tsx
Labels: 🌏 deployment

#142 이미지 경로 수정하여 배포합니다.
  src/app/(auth)/sign-up/layout.tsx
Labels: 🌏 deployment
